### ISSUE TITLE
Checklist close bracket must be followed by space - Document via lists_test.rb

### ISSUE THREAD

**Issue by sturtison** [asciidoctor/asciidoctor#3321]
User story:

Asciidoc is excellent for the documents we write, and we want checklists and following text to line up in the source text and the render. Using a misconfigured editor that embedded tabs lead to this possible issue.

Issue: 

A checklist [x] immediately followed by a \t, optional space, then text, renders the line as text, `[x] my checklist`.
A checklist [x] immediately followed by a space then \t, renders as expected.

- Without an editor revealing whitespace characters, the input text looks normal.
- The behaviour at different list levels, adding a list glyph, then repeating the text including the [x] leads me to think that this is not behaving as expected.
- There is no test to cover this specifically in [lists_test.rb](https://github.com/asciidoctor/asciidoctor/blob/35c1f9a8f7c1cee310d6c1d1ad46ec5ae4702d54/test/lists_test.rb#L5136)
- The behaviour is consistent (as expected) across generated HTML and in VSCode preview using AsciidoctorJS.

Example:

```asciidoctor
* [x]     Closing bracket followed by space, renders as expected.
* [x]	   <tab><space..>after closing bracket. Fail.
**      [x]	   As above, second level: A 2nd level checklist glyph is rendered, plus the text `[x] As above ...`
* [x]     Closing bracket followed by space, renders as expected.
```
Render of the above:
![image](https://user-images.githubusercontent.com/13049926/58928326-ba111980-875a-11e9-9314-fa15911816c2.png)

Is this working as designed?

**Comment by mojavelinux** [comment]
What you're describing is working as expected. In order for the checkbox (`[x]`, `[*]`, or `[ ]`) to be processed, it must be followed by a space.

The second item is not a fail, necessarily. Once the list has been converted to a checklist, it does not have bullets. So while it looks like something is missing at the start of the line, it's actually what a list item without a checkbox looks like in a checklist.

I could add a test to verify that a checkbox followed by a tab is not recognized.

**Comment by mojavelinux** [comment]
I have proposed a test in #3326.
